### ISSUE TITLE
新版本采用toml进行配置化，复制集部署，主本建立索引，sync进程直接死掉。

### ISSUE THREAD

**Issue by brzone** [caosiyang/py-mongo-sync#20]
在您的最新版本toml配置化中，这边是复制集部署(一主二从)，但是发现，只要在主本建立索引，sync进程会直接死掉。 不管是建立索引的集合是大还是小。而且在log中也没有任何输出 。阅读了您的sync代码，但是还是没找到具体原因。
    曾经也用过你的旧版本（非toml配置化），当建立索引的集合数量不是很大(低于亿条数据)，不会死掉，但是如果超过一定数量级（比如：亿级数量），sync进程也会死掉（用ps找不到进程）。
     考虑过超时的问题，但是建立小集合（瞬间完成），sync进程也会一样死掉。
    不知道你对此有何看法。

**Comment by caosiyang** [comment]
程序没有抛异常吗？另外你的mongo用的是什么版本？建的是什么样的索引？方便提供一下么

**Comment by brzone** [comment]
在toml中配置的log文件中，没有任何异常信息。
版本号是: 3.4.2，索引就是简单的索引，如：db.user.ensureIndex({ "name" : 1 },{ "background" : true });

**Comment by caosiyang** [comment]
程序崩溃时的异常信息输出到stderr，你可以前台跑个同步，看下是什么异常。
另外，我在测试环境下同步过程中建立索引是正常的。

**Comment by brzone** [comment]
你 这么一说，我想起，我的程序是放在后台执行，在nohup.out中，有打印多次：
Traceback (most recent call last):
  File "./sync.py", line 29, in <module>
    syncer.run()
  File "/data/soft/py-mongo-sync-master/mongosync/synchronizer.py", line 67, in run
    self._sync()
  File "/data/soft/py-mongo-sync-master/mongosync/synchronizer.py", line 96, in _sync
    self._sync_oplog(oplog_start)
  File "/data/soft/py-mongo-sync-master/mongosync/mongo_synchronizer.py", line 199, in _sync_oplog
    self._dst.replay_oplog(dst_dbname, dst_collname, oplog)
  File "/data/soft/py-mongo-sync-master/mongosync/db.py", line 141, in replay_oplog
    self._mc[dbname][collname].replace_one({'_id': oplog['o']['_id']}, oplog['o'], upsert=True)
KeyError: '_id'

应该就是每次建立索引，sync进行同步抛出的异常。


而在您的以前版本（非toml配置化），在nohup.out，有异常信息：
Traceback (most recent call last):
  File "./sync.py", line 44, in <module>
    syncer.run()
  File "/data/soft/py-mongo-sync-master/mongosync/mongo_synchronizer.py", line 538, in run
    self._sync()
  File "/data/soft/py-mongo-sync-master/mongosync/mongo_synchronizer.py", line 133, in _sync
    self._sync_oplog(oplog_start)
  File "/data/soft/py-mongo-sync-master/mongosync/mongo_synchronizer.py", line 352, in _sync_oplog
    self._replay_oplog(oplog)
  File "/data/soft/py-mongo-sync-master/mongosync/mongo_synchronizer.py", line 430, in _replay_oplog
    self._replay_oplog_mongodb(oplog)
  File "/data/soft/py-mongo-sync-master/mongosync/mongo_synchronizer.py", line 466, in _replay_oplog_mongodb
    self._dst_mc[dbname][collname].insert_one(oplog['o'])
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 670, in insert_one
    bypass_doc_val=bypass_document_validation),
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 575, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 556, in _insert_one
    check_keys=check_keys)
  File "/usr/lib64/python2.7/site-packages/pymongo/pool.py", line 482, in command
    self._raise_connection_failure(error)
  File "/usr/lib64/python2.7/site-packages/pymongo/pool.py", line 610, in _raise_connection_failure
    raise error
bson.errors.InvalidDocument: key '$exists' must not start with '$'

**Comment by caosiyang** [comment]
索引操作的oplog有两种格式，一种是command，一种是insert，根据上面异常，都是在insert这种形式下发生的，这样，你用dev分支吧，https://github.com/caosiyang/py-mongo-sync/tree/dev
这个分支已经解决了这个问题，近期将合并至master。

**Comment by brzone** [comment]
ok,thanks ! 叨扰你多次了，再次感谢。
