### ISSUE TITLE
sync issue

### ISSUE THREAD

**Issue by wavelet123** [caosiyang/py-mongo-sync#5]
hi,
能否帮忙看下，同步增量数据的时候报错。全量19亿记录都同步好了。
Traceback (most recent call last):
  File "./sync.py", line 149, in <module>
    syncer.run()
  File "/root/py-mongo-sync-master/mongo_synchronizer.py", line 595, in run
    self._sync()
  File "/root/py-mongo-sync-master/mongo_synchronizer.py", line 129, in _sync
    self._sync_oplog(oplog_start)
  File "/root/py-mongo-sync-master/mongo_synchronizer.py", line 466, in _sync_oplog
    self._replay_oplog(oplog)
  File "/root/py-mongo-sync-master/mongo_synchronizer.py", line 519, in _replay_oplog
    self._replay_oplog_mongodb(oplog)
  File "/root/py-mongo-sync-master/mongo_synchronizer.py", line 549, in _replay_oplog_mongodb
    self._dst_mc[dbname].command(oplog['o'])
  File "/usr/lib64/python2.6/site-packages/pymongo/database.py", line 494, in command
    codec_options, **kwargs)
  File "/usr/lib64/python2.6/site-packages/pymongo/database.py", line 406, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/lib64/python2.6/site-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/usr/lib64/python2.6/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/lib64/python2.6/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: ns not found

**Comment by wavelet123** [comment]
方便给个 qq 私聊一下吗？实在不好意思，打扰了。

**Comment by caosiyang** [comment]
50339723

**Comment by caosiyang** [comment]
同步指定集合时，回放同一个数据库下其他集合的oplog，发生"namespace not found"
